DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS REQUEST;
DROP TABLE IF EXISTS DISH; 
DROP TABLE IF EXISTS OWNER;
DROP TABLE IF EXISTS RESTAURANT;
DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS FAVORITE_DISH;
DROP TABLE IF EXISTS FAVORITE_RESTAURANT;
DROP TABLE IF EXISTS REQUEST_DISH;

CREATE TABLE USER (
    username INT NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    nome VARCHAR(80) NOT NULL,
    address VARCHAR(80) NOT NULL,
    phone INT,
    CONSTRAINT PK_USER PRIMARY KEY (username)
);

CREATE TABLE OWNER (
    username INT NOT NULL,
    idRestaurant INT NOT NULL,
    CONSTRAINT PK_OWNER PRIMARY KEY (username),
    FOREIGN KEY (username) REFERENCES USER,
    FOREIGN KEY (idRestaurant) REFERENCES RESTAURANT
);

CREATE TABLE REQUEST (
    idRequest INT NOT NULL,
    username INT NOT NULL, 
    idRestaurant INT NOT NULL, 
    state VARCHAR(15) NOT NULL,
    CONSTRAINT PK_REQUEST PRIMARY KEY (idRequest),
    FOREIGN KEY (username) REFERENCES USER,
    FOREIGN KEY (idRestaurant) REFERENCES RESTAURANT
);

CREATE TABLE DISH (
    idDish INT NOT NULL,
    name VARCHAR(80) NOT NULL,
    price FLOAT NOT NULL,
    promotion INT,
    category VARCHAR(50),
    CONSTRAINT PK_DISH PRIMARY KEY (idDish)
);

CREATE TABLE RESTAURANT (
    idRestaurant INT NOT NULL,
    name VARCHAR(80) NOT NULL,
    address VARCHAR(80),
    category VARCHAR(50),
    photo VARCHAR(150),
    CONSTRAINT PK_RESTAURANT PRIMARY KEY (idRestaurant)
);

CREATE TABLE REVIEW (
    idReview INT NOT NULL,
    username INT NOT NULL,
    rating INT NOT NULL,
    fullText VARCHAR(120),
    data DATE NOT NULL,
    CONSTRAINT PK_REVIEW PRIMARY KEY (idReview),
    FOREIGN KEY (username) REFERENCES USER
);

CREATE TABLE COMMENT (
    idComment INT NOT NULL, 
    username INT NOT NULL,
    idReview INT NOT NULL,
    fulltext VARCHAR(120),
    CONSTRAINT PK_COMMENT PRIMARY KEY (idComment),
    FOREIGN KEY (username) REFERENCES USER,
    FOREIGN KEY (idReview) REFERENCES REVIEW
);

CREATE TABLE FAVORITE_DISH (
    username INT NOT NULL,
    idDish INT NOT NULL,
    CONSTRAINT PK_FAV_DISH PRIMARY KEY (username, idDish),
    FOREIGN KEY (username) REFERENCES USER,
    FOREIGN KEY (idDish) REFERENCES DISH
);

CREATE TABLE FAVORITE_RESTAURANT (
    username INT NOT NULL,
    idRestaurant INT NOT NULL,
    CONSTRAINT PK_FAV_RESTAURANT PRIMARY KEY (username, idRestaurant),
    FOREIGN KEY (username) REFERENCES USER,
    FOREIGN KEY (idRestaurant) REFERENCES RESTAURANT
);

CREATE TABLE REQUEST_DISH (
    idRequest INT NOT NULL,
    idDish INT NOT NULL,
    CONSTRAINT PK_REQUEST_DISH PRIMARY KEY (idRequest, idDish),
    FOREIGN KEY (idRequest) REFERENCES REQUEST,
    FOREIGN KEY (idDish) REFERENCES DISH
);